### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by mashuDuek** [jessewarren-aa/strifechat#2]
Looks good as well! 
Couple things: 
1. I would camel case everything as the state is to be manipulated in frontend with js.
2. channels should probably have a list of user_ids? 
3. In messageReactions slice you include nothing but foreign keys, one of which references a slice you don't have (reactions). In the schema issue i mentioned i wouldn't have reactions in there as a table. I take that back, in order for reactions to be easier to manipulate in the frontend ids would be cool to have. In which case the messageReactions slice is exactly how I would handle it as well. Good job. 
4. userRoles, do we care about anyone elses role other than current user? 

Rest looks good.

**Comment by jessewarren-aa** [comment]
@mashuDuek 

1. Camel case completed.
2. Discord is unlike Slack: users do not opt to join or leave channels; rather, joining a server will put the user into all channels. From the server's end of things, it can prevent users from viewing channels by using roles. From the user's end, they can choose to hide channels; this will not actually remove them from the channel and they can still be seen/tagged in it.
3. To clarify, would you recommend that I make a change by adding a slice of `reactions`, or leave it as is?
4. We do technically, to hold true to my response in the Schema issue: custom roles means certain users will both share permissions such as deleting messages. Discord role hierarchy dictates that a role that is higher than another (they use a drag and drop system that I won't implement) means that the role beneath cannot take that kind of actions against a user with a role higher than their own (i.e., an admin may be able to delete messages but may not delete messages from the owner).

Let me know if this is all set to go!

**Comment by mashuDuek** [comment]
Okay, yeah we gotta chat. This seems awesome. I'll grab you later
