### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by jessewarren-aa** [jessewarren-aa/strifechat#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by SergeyGridin** [comment]
- [ ] Logout button is not being displayed

**Comment by SergeyGridin** [comment]
- [ ] Errors persist when you switch between forms. We want errors to be cleared every time you click between login/signup

**Comment by jessewarren-aa** [comment]
Error persistence is resolved.
